# Generated by Django 4.1.7 on 2023-02-17 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Область",
                "verbose_name_plural": "Область",
            },
        ),
        migrations.CreateModel(
            name="DataCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="Название")),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_criteria",
                        to="datastorage.datacriteria",
                        verbose_name="Старший критерий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Критерий данных",
                "verbose_name_plural": "Критерий данных",
            },
        ),
        migrations.CreateModel(
            name="DataName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Название данных",
                "verbose_name_plural": "Название данных",
            },
        ),
        migrations.CreateModel(
            name="DataSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Раздел данных",
                "verbose_name_plural": "Раздел данных",
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Округ",
                "verbose_name_plural": "Округ",
            },
        ),
        migrations.CreateModel(
            name="DataValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField(verbose_name="Значение")),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="datastorage.area",
                        verbose_name="Область",
                    ),
                ),
                (
                    "criteria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="datastorage.datacriteria",
                        verbose_name="Критерий",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="datastorage.dataname",
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Область",
                "verbose_name_plural": "Область",
            },
        ),
        migrations.AddField(
            model_name="dataname",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="names",
                to="datastorage.datasection",
                verbose_name="Раздел",
            ),
        ),
        migrations.AddField(
            model_name="datacriteria",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="criteria",
                to="datastorage.datasection",
                verbose_name="Раздел",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="areas",
                to="datastorage.district",
                verbose_name="Округ",
            ),
        ),
    ]
