# Generated by Django 4.1.7 on 2023-02-18 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=1024, verbose_name="Название")),
                (
                    "head_uuids",
                    models.TextField(blank=True, null=True, verbose_name="История"),
                ),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_areas",
                        to="datastorage.area",
                        verbose_name="Старший",
                    ),
                ),
            ],
            options={
                "verbose_name": "География",
                "verbose_name_plural": "География",
            },
        ),
        migrations.CreateModel(
            name="DataCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Критерий данных",
                "verbose_name_plural": "Критерий данных",
            },
        ),
        migrations.CreateModel(
            name="DataCriteriaUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Единица измерения критерия данных",
                "verbose_name_plural": "Единица измерения критерия данных",
            },
        ),
        migrations.CreateModel(
            name="DataName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="Название")),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_names",
                        to="datastorage.dataname",
                        verbose_name="Старший название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Название данных",
                "verbose_name_plural": "Название данных",
            },
        ),
        migrations.CreateModel(
            name="DataSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Раздел данных",
                "verbose_name_plural": "Раздел данных",
            },
        ),
        migrations.CreateModel(
            name="DataValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField(verbose_name="Значение")),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="datastorage.area",
                        verbose_name="Область",
                    ),
                ),
                (
                    "criteria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="datastorage.datacriteria",
                        verbose_name="Критерий",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="datastorage.dataname",
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение",
                "verbose_name_plural": "Значение",
            },
        ),
        migrations.AddField(
            model_name="dataname",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="names",
                to="datastorage.datasection",
                verbose_name="Раздел",
            ),
        ),
        migrations.AddField(
            model_name="datacriteria",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="criteria",
                to="datastorage.datasection",
                verbose_name="Раздел",
            ),
        ),
        migrations.AddField(
            model_name="datacriteria",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="criteria",
                to="datastorage.datacriteriaunit",
                verbose_name="Единица измерения",
            ),
        ),
    ]
