# Generated by Django 4.1.7 on 2023-02-17 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datastorage", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="area",
            options={"verbose_name": "География", "verbose_name_plural": "География"},
        ),
        migrations.AlterModelOptions(
            name="datavalue",
            options={"verbose_name": "Значение", "verbose_name_plural": "Значение"},
        ),
        migrations.RemoveField(
            model_name="area",
            name="district",
        ),
        migrations.AddField(
            model_name="area",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_areas",
                to="datastorage.area",
                verbose_name="Старший",
            ),
        ),
        migrations.DeleteModel(
            name="District",
        ),
    ]
