# Generated by Django 4.1.7 on 2023-02-18 00:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("datastorage", "0002_alter_area_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
