# Generated by Django 4.1.7 on 2023-02-17 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datastorage", "0002_alter_area_options_alter_datavalue_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datacriteria",
            name="head",
        ),
        migrations.AddField(
            model_name="dataname",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_name",
                to="datastorage.dataname",
                verbose_name="Старший название",
            ),
        ),
    ]
