# Generated by Django 4.1.7 on 2023-02-17 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datastorage", "0003_remove_datacriteria_head_dataname_head"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataCriteriaUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Единица измерения критерия данных",
                "verbose_name_plural": "Единица измерения критерия данных",
            },
        ),
        migrations.AddField(
            model_name="datacriteria",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="criteria",
                to="datastorage.datacriteriaunit",
                verbose_name="Единица измерения",
            ),
        ),
    ]
