# Generated by Django 4.1.7 on 2023-02-17 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datastorage", "0004_datacriteriaunit_datacriteria_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="datavalue",
            name="date",
            field=models.DateField(default="2022-01-01", verbose_name="Дата"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dataname",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_names",
                to="datastorage.dataname",
                verbose_name="Старший название",
            ),
        ),
    ]
